# Site settings
title: Adam's website
email: amikhitarian@albany.edu
description: Adam is super cool
url: http://mickeytarian.github.io
github_username: mickeytarian
color: red

# Build settings
markdown: kramdown
permalink: pretty
